### ISSUE TITLE
not working under R 3.5.1

### ISSUE THREAD

**Issue by mrke** [pmjherman/r-ncdf4-build-opendap-windows#1]
Dear Peter,

First, thanks for the package! It's really great to have. But unfortunately it seems to no longer work under the new R v3.5.1. Are you able to make it work?

Many thanks,
Mike

**Comment by pmjherman** [comment]
No idea what has gone wrong. I will have a look at it, but the matter is complicated and I am not sure I will be able to make it work again. It may take some time...

**Comment by pmjherman** [comment]
The issue has finally be solved. Sorry it took me so long, but I was stuck and could not easily find the solution. In the end it appeared to be a matter of quotes not correctly placed...

**Comment by mrke** [comment]
That’s great – thanks Peter. I have also since discovered the RNetCDF package which has opendap connectivity on multiple platforms.
